/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetomdi.Frames;

import static config.config.LOG_FILE;
import java.util.List;
import javax.swing.JOptionPane;
import projetomdi.Classes.CadastroCliente;
import projetomdi.Listener.AtualizarListener;
import projetomdi.LogFile.LogFiles;
import projetomdi.Service.ClientesDAO;

/**
 *
 * @author CLIENTE
 */
public class AtualizarCliente extends javax.swing.JInternalFrame {

    AtualizarListener listener = new AtualizarListener(this);
    ClientesDAO clientesDao;
    private String currentUser;
    TelaPrincipal tela;

    public String getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
    }

    public AtualizarCliente(String user, TelaPrincipal tela) {
        this.clientesDao = new ClientesDAO(currentUser);
        this.tela = tela;
        initComponents();
        setCurrentUser(user);

    }

    public void buscar() {

        if (clienteCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos Vazios");

        } else {
            try {
                CadastroCliente cliente = clientesDao.getCadastroCliente(Integer.parseInt(clienteCodigo.getText().replaceAll("[^0-9]", "")));
                Cadastro cdCliente = new Cadastro(currentUser, cliente);
                cdCliente.setVisible(true);
                tela.add(cdCliente);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar, por favor, tente novamente");
                LogFiles.setFileContentAsStackTrace(LOG_FILE, e, currentUser);
            }

        }

    }

    public void verCliente() {
        try {
            List<CadastroCliente> clientes = clientesDao.getAll();
            String clienteMessage = "";
            for (CadastroCliente cliente1 : clientes) {
                clienteMessage += cliente1.getCodigo() + " - " + cliente1.getNome() + "\n";
            }
            JOptionPane.showMessageDialog(this, clienteMessage, "Clientes Disponíveis", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar, por favor, tente novamente");
            LogFiles.setFileContentAsStackTrace(LOG_FILE, e, currentUser);
        }

    }

    public void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Realmente deseja Sair?", "Confirmação Sair", JOptionPane.YES_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    public void TelaCadastro(CadastroCliente cliente) {
        Cadastro cdCliente = new Cadastro(currentUser, cliente);
        cdCliente.setVisible(true);
        tela.add(cdCliente);
        LogFiles.setFileContentAsStackTrace(LOG_FILE, currentUser + " acessou Cadastro");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        btnSair = new javax.swing.JButton();
        cliente2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        verClientes = new javax.swing.JButton();
        clienteCodigo = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        btnSair.addActionListener(listener);
        btnSair.setActionCommand("sair");
        btnSair.setText("Sair");

        cliente2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cliente2.setText("Código");

        btnBuscar.addActionListener(listener);
        btnBuscar.setActionCommand("buscar");
        btnBuscar.setText("Buscar");

        verClientes.addActionListener(listener);
        verClientes.setActionCommand("verCliente");
        verClientes.setText("Ver clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cliente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente2)
                    .addComponent(verClientes)
                    .addComponent(clienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSair))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel cliente2;
    private javax.swing.JTextField clienteCodigo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JButton verClientes;
    // End of variables declaration//GEN-END:variables
}
