CREATE TABLE livros
(
codigo INTEGER NOT NULL PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
autor VARCHAR(45) NOT NULL,
ano INTEGER NOT NULL,
num_paginas INTEGER NOT NULL,
genero VARCHAR(45) NOT NULL,
editora VARCHAR(45) NOT NULL,
quantidade INTEGER NOT NULL
)